home/urls.py
from django.urls import path
from .views import all_science

urlpatterns = [
    path('', all_science, name='all_science')
]

mathematics/urls.py
from django.urls import path
from .views import all_lesson, lesson

app_name = 'mathematics'

urlpatterns = [
    path('', all_lesson, name='all_lesson'),
    path('lesson/<int:lesson_id>', lesson, name='lesson') 
]

philosophy/urls.py
from django.urls import path
from .views import philosophy_all_lesson, philosophy_lesson

app_name = 'philosophy'

urlpatterns = [
    path('', philosophy_all_lesson, name='philosophy_all_lesson'),
    path('philosophy_lesson/<int:lesson_id>', philosophy_lesson, name='philosophy_lesson') 
] 

school_sciences/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import all_science
from philosophy.views import philosophy_all_lesson

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mathematics/',include('mathematics.urls')),
    path('philosophy/',include('philosophy.urls'))
]

home/models.py
from django.db import models

# Create your models here.

mathematics/models.py
from django.db import models

# Create your models here.
class Science(models.Model):
    lesson = models.CharField(max_length=150)
    teacher = models.CharField(max_length=20)
    date = models.DateField()
    description = models.TextField()
    url = models.URLField(blank=True)

philosophy/models.py
from django.db import models

# Create your models here.
class SciencePhilosophy(models.Model):
    lesson = models.CharField(max_length=150)
    teacher = models.CharField(max_length=20)
    date = models.DateField()
    description = models.TextField()
    url = models.URLField(blank=True)

home/views.py
from django.shortcuts import render

# Create your views here.
def all_science(request):
    return render(request,'school_sciences/home.html')

mathematics/views.py
from django.shortcuts import render, get_list_or_404
from .models import Science

# Create your views here.
def all_lesson(request):
    sciences = Science.objects.all()
    return render(request,'mathematics/lessons.html', {'sciences': sciences})

def lesson(request,lesson_id):
    sciencess = get_list_or_404(Science,pk=lesson_id)
    print(len(sciencess),'bittaaaaa')
    return render(request,'mathematics/lesson.html',{'sciencess': sciencess})

philosophy/views.py
from django.shortcuts import render, get_list_or_404
from .models import SciencePhilosophy

def philosophy_all_lesson(request):
    sciences = SciencePhilosophy.objects.all()
    return render(request,'philosophy/lessons.html', {'sciences': sciences})

def philosophy_lesson(request,lesson_id):
    sciencess = get_list_or_404(SciencePhilosophy,pk=lesson_id)
    return render(request,'philosophy/lesson.html',{'sciencess': sciencess})

home/templates/school_sciences/home.html
<h1>Fanlar ro`yxati</h1>
<a href="{% url 'mathematics:all_lesson' %}">matematika</a>    
<!-- bu yerdagi 'all_lesson',  mathematics/urls ichidagi name=all_lesson dan olingan-->
<a href="{% url 'philosophy:philosophy_all_lesson' %}">fizika</a>    

mathematics/templates/mathematics/lesson.html
{% load static %}
{% for sciences in sciencess %}
<h1>mavzu: {{sciences.lesson}}</h1>

<h3>{{sciences.date}}</h3>
<h3>{{sciences.description}}</h3>
<a href="{{sciences.url}}">yuklash</a>

{% endfor %}

mathematics/templates/mathematics/lessons.html
<h1>Mavzular ro`yxati</h1>


<table border="2px">
    <tr>
        <td>Lessons</td>
        <td>teachers</td>
        <td>date</td>
    </tr>
    {% for science in sciences %}
    <tr>
        <td><a href="{% url 'mathematics:lesson' science.id %}"><h3>{{science.lesson}}</h3></a></td>
        <td><h3>{{science.teacher}}</h3></td>
        <td><h3>{{science.date}}</h3></td>
    </tr>
    
    {% endfor %}
</table>

philosophy/templates/philosophy/lesson.html
{% load static %}
{% for sciences in sciencess %}
<h1>mavzu: {{sciences.lesson}}</h1>

<h3>{{sciences.date}}</h3>
<h3>{{sciences.description}}</h3>
<a href="{{sciences.url}}">yuklash</a>

{% endfor %}

philosophy/templates/philosophy/lessons.html
<h1>Fizikadan mavzular ro`yxati</h1>


<table border="2px">
    <tr>
        <td>id</td>
        <td>Lessons</td>
        <td>teachers</td>
        <td>date</td>
    </tr>
    {% for science in sciences %}
    <tr>
        <td>{{science.id}}</td>
        <td><a href="{% url 'philosophy:lesson' science.id %}"><h3>{{science.lesson}}</h3></a></td>
        <td><h3>{{science.teacher}}</h3></td>
        <td><h3>{{science.date}}</h3></td>
    </tr>
    
    {% endfor %}
</table>